apiVersion: v1
kind: Pod
metadata:
  name: pod-test01
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello cubastion; sleep 5; done"]
    - name: c01
      image: httpd
      ports:
        - containerPort: 80

